# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import uic
from PyQt5.QtWidgets import QApplication


class Calendar:
    def __init__(self, ui_path):
        self.ui = uic.loadUi(ui_path)


app = QApplication(sys.argv)
calendar = Calendar("../ui/scan_display_main.ui")
calendar.ui.show()
app.exec_()
